import Splash from './Splash/Splash';
import HomeScreen from './HomeScreen/HomeScreen';
import AnimeHomeScreen from './AnimeHomeScreen/AnimeHomeScreen';
import SearchScreen from './SearchScreen/SearchScreen';
import SeriesScreen from './SeriesScreen/SeriesScreen';
import GenresScreen from './GenresScreen/GenresScreen';
import ActionScreen from './ActionScreen/ActionScreen';
import SettingsScreen from './SettingsScreen/SettingsScreen';
import PremiumScreen from './PremiumScreen/PremiumScreen';
import NotificationScreen from './NotificationScreen/NotificationScreen';
import PrivacyPolicyScreen from './PrivacyPolicyScreen/PrivacyPolicyScreen';
import RateUsScreen from './RateUsScreen/RateUsScreen';
export {Splash,HomeScreen,AnimeHomeScreen,SearchScreen,SeriesScreen,GenresScreen,ActionScreen,SettingsScreen,PremiumScreen,NotificationScreen,PrivacyPolicyScreen,RateUsScreen};
